version: "3"

networks:
  k8sample:
      driver: overlay

services:
  angularweb:
    image: srikanthpalla/db-details-angular
    container_name: angularweb
    ports:
      - "9191:80"
    networks:
      - k8sample

  counterweb:
    image: srikanthpalla/db-details-boot
    container_name: counterweb
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
    networks:
      - k8sample

  mysqldb:
    image: srikanthpalla/db-details-mysql
    container_name: mysqldb
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - "db-data:/var/lib/mysql"
    networks:
      - k8sample

  prometheus:
    image: prom/prometheus:0.18.0
    volumes:
        - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
        - '-config.file=/etc/prometheus/prometheus.yml'
    ports:
        - '9090:9090'
    networks:
      - k8sample

  node-exporter:
    image: prom/node-exporter:0.12.0rc1
    ports:
        - '9100:9100'
    networks:
      - k8sample

  grafana:
    image: grafana/grafana:3.0.0-beta7
    environment:
        - GF_SECURITY_ADMIN_PASSWORD=pass
    depends_on:
        - prometheus
    ports:
        - "3000:3000"
    networks:
      - k8sample
volumes:
  db-data:
