# prometheus.yml
global:
    scrape_interval: 5s
    external_labels:
        monitor: 'k8-monitor'
scrape_configs:
    - job_name: 'prometheus'
      target_groups:
          - targets: ['counterweb:8080']
    - job_name: 'node-exporter'
      target_groups:
          - targets: ['node-exporter:9100']